import React from 'react';
import { Sparkles, Brain, Zap } from 'lucide-react';
import { cn } from '~/lib/utils';

interface ModelBadgeProps {
  model?: string;
  className?: string;
}

// Model configuration with colors and icons
const modelConfig: Record<string, { label: string; color: string; bgColor: string; borderColor: string; icon: typeof Sparkles }> = {
  // OpenAI Models - Blue/Teal
  'gpt-4o': { label: 'GPT-4o', color: 'text-blue-700 dark:text-blue-300', bgColor: 'bg-blue-50 dark:bg-blue-950/30', borderColor: 'border-blue-200 dark:border-blue-800/50', icon: Zap },
  'gpt-5.2': { label: 'GPT-5.2', color: 'text-blue-700 dark:text-blue-300', bgColor: 'bg-blue-50 dark:bg-blue-950/30', borderColor: 'border-blue-200 dark:border-blue-800/50', icon: Zap },
  'gpt-5.1': { label: 'GPT-5.1', color: 'text-blue-700 dark:text-blue-300', bgColor: 'bg-blue-50 dark:bg-blue-950/30', borderColor: 'border-blue-200 dark:border-blue-800/50', icon: Zap },
  'gpt-5-nano': { label: 'GPT-5 Nano', color: 'text-cyan-700 dark:text-cyan-300', bgColor: 'bg-cyan-50 dark:bg-cyan-950/30', borderColor: 'border-cyan-200 dark:border-cyan-800/50', icon: Zap },
  'gpt-5-mini': { label: 'GPT-5 Mini', color: 'text-teal-700 dark:text-teal-300', bgColor: 'bg-teal-50 dark:bg-teal-950/30', borderColor: 'border-teal-200 dark:border-teal-800/50', icon: Zap },

  // Anthropic Models - Purple
  'claude-sonnet-4': { label: 'Claude Sonnet 4', color: 'text-purple-700 dark:text-purple-300', bgColor: 'bg-purple-50 dark:bg-purple-950/30', borderColor: 'border-purple-200 dark:border-purple-800/50', icon: Brain },
  'claude-opus-4.5': { label: 'Claude Opus 4.5', color: 'text-purple-700 dark:text-purple-300', bgColor: 'bg-purple-50 dark:bg-purple-950/30', borderColor: 'border-purple-200 dark:border-purple-800/50', icon: Brain },

  // Google Models - Orange/Amber
  'gemini-2.5-flash': { label: 'Gemini 2.5 Flash', color: 'text-orange-700 dark:text-orange-300', bgColor: 'bg-orange-50 dark:bg-orange-950/30', borderColor: 'border-orange-200 dark:border-orange-800/50', icon: Sparkles },
  'gemini-3-flash': { label: 'Gemini 3 Flash', color: 'text-amber-700 dark:text-amber-300', bgColor: 'bg-amber-50 dark:bg-amber-950/30', borderColor: 'border-amber-200 dark:border-amber-800/50', icon: Sparkles },
  'gemini-3-pro': { label: 'Gemini 3 Pro', color: 'text-amber-700 dark:text-amber-300', bgColor: 'bg-amber-50 dark:bg-amber-950/30', borderColor: 'border-amber-200 dark:border-amber-800/50', icon: Sparkles },
};

export function ModelBadge({ model, className }: ModelBadgeProps) {
  // Don't render if no model specified
  if (!model) return null;

  // Get model config or use default
  const config = modelConfig[model] ?? {
    label: model,
    color: 'text-slate-700 dark:text-slate-300',
    bgColor: 'bg-slate-50 dark:bg-slate-950/30',
    borderColor: 'border-slate-200 dark:border-slate-800/50',
    icon: Sparkles,
  };

  const Icon = config.icon;

  return (
    <div
      className={cn(
        'inline-flex items-center gap-1 px-2 py-0.5 rounded-md border text-[10px] font-semibold uppercase tracking-wider transition-colors',
        config.bgColor,
        config.color,
        config.borderColor,
        className
      )}
      title={`Generated by ${config.label}`}
    >
      <Icon className="w-2.5 h-2.5" />
      <span>{config.label}</span>
    </div>
  );
}
