import type { LegalTemplate } from "./template-registry";

export interface EditorSection {
  id: string;
  type: "title" | "heading" | "paragraph";
  label?: string;
  content: string;
  editable?: boolean;
}

type SectionBuilder = (data: Record<string, string>) => EditorSection[];

function m(data: Record<string, string>, key: string): string {
  const val = data[key] || `[${key}]`;
  return `<mark>${val}</mark>`;
}

const SECTION_BUILDERS: Record<string, SectionBuilder> = {
  nda: (data) => [
    { id: "header", type: "title", content: "NON-DISCLOSURE AGREEMENT", editable: false },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This Non-Disclosure Agreement (the "Agreement") is entered into as of ${m(data,"effective_date")} (the "Effective Date") by and between:` },
    { id: "parties_heading", type: "heading", content: "1. Parties" },
    { id: "dp_details", type: "paragraph", label: "Disclosing Party",
      content: `<strong>Disclosing Party:</strong> ${m(data,"disclosing_party_name")}, a ${m(data,"disclosing_party_type")} organized under the laws of ${m(data,"disclosing_party_jurisdiction")}, with its principal office at ${m(data,"disclosing_party_address")} (the "Disclosing Party");` },
    { id: "rp_details", type: "paragraph", label: "Receiving Party",
      content: `<strong>Receiving Party:</strong> ${m(data,"receiving_party_name")}, a ${m(data,"receiving_party_type")} organized under the laws of ${m(data,"receiving_party_jurisdiction")}, with its principal office at ${m(data,"receiving_party_address")} (the "Receiving Party").` },
    { id: "purpose_heading", type: "heading", content: "2. Purpose" },
    { id: "purpose", type: "paragraph", label: "Purpose",
      content: `The Disclosing Party wishes to disclose certain confidential information to the Receiving Party for the purpose of ${m(data,"purpose")} (the "Purpose").` },
    { id: "ci_heading", type: "heading", content: "3. Definition of Confidential Information" },
    { id: "ci_body", type: "paragraph", label: "Confidential Info",
      content: `"Confidential Information" means any and all non-public, proprietary, or confidential information disclosed by the Disclosing Party to the Receiving Party, whether orally, in writing, electronically, or by any other means, including but not limited to: ${m(data,"confidential_info_description")}.` },
    { id: "obligations_heading", type: "heading", content: "4. Obligations of Receiving Party" },
    { id: "obligations", type: "paragraph", label: "Obligations",
      content: `The Receiving Party agrees to: (a) hold the Confidential Information in strict confidence; (b) not disclose the Confidential Information to any third party without prior written consent; (c) use the Confidential Information solely for the Purpose; and (d) protect the Confidential Information using at least the same degree of care it uses to protect its own confidential information, but in no event less than reasonable care.` },
    { id: "term_heading", type: "heading", content: "5. Term and Termination" },
    { id: "term", type: "paragraph", label: "Term",
      content: `This Agreement shall remain in effect for a period of ${m(data,"term_years")} year(s) from the Effective Date, unless earlier terminated by either party with ${m(data,"notice_days")} days' written notice. The obligations of confidentiality shall survive termination for a period of ${m(data,"survival_years")} year(s).` },
    { id: "law_heading", type: "heading", content: "6. Governing Law" },
    { id: "law", type: "paragraph", label: "Governing Law",
      content: `This Agreement shall be governed by and construed in accordance with the laws of ${m(data,"governing_law_jurisdiction")}, without regard to its conflict of law provisions.` },
    { id: "sig_heading", type: "heading", content: "7. Signatures" },
    { id: "sig_dp", type: "paragraph", label: "Disclosing Party Signature",
      content: `<strong>Disclosing Party:</strong><br/>Name: ${m(data,"disclosing_party_signatory")}<br/>Title: ${m(data,"disclosing_party_signatory_title")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_rp", type: "paragraph", label: "Receiving Party Signature",
      content: `<strong>Receiving Party:</strong><br/>Name: ${m(data,"receiving_party_signatory")}<br/>Title: ${m(data,"receiving_party_signatory_title")}<br/>Date: ${m(data,"signature_date")}` },
  ],

  founders_agreement: (data) => [
    { id: "header", type: "title", content: "FOUNDERS AGREEMENT", editable: false },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This Founders Agreement is entered into as of ${m(data,"effective_date")} by and among the undersigned Founders, in connection with the formation and operation of ${m(data,"company_name")}.` },
    { id: "s1_heading", type: "heading", content: "1. Parties and Company Formation" },
    { id: "s1_body", type: "paragraph", label: "Company Details",
      content: `The Company shall be organized as a ${m(data,"company_type")} under the laws of ${m(data,"company_jurisdiction")}, with its principal place of business at ${m(data,"company_address")}.` },
    { id: "s1_founders", type: "paragraph", label: "Founders",
      content: `<strong>Founder 1:</strong> ${m(data,"founder_1_name")}, serving as ${m(data,"founder_1_title")}.<br/><strong>Founder 2:</strong> ${m(data,"founder_2_name")}, serving as ${m(data,"founder_2_title")}.` },
    { id: "s2_heading", type: "heading", content: "2. Business Purpose" },
    { id: "s2_body", type: "paragraph", label: "Business Description",
      content: `The Company is being formed for the purpose of: ${m(data,"business_description")}. The Founders agree to devote their full-time efforts, skill, and attention to the business and affairs of the Company.` },
    { id: "s3_heading", type: "heading", content: "3. Equity Allocation" },
    { id: "s3_body", type: "paragraph", label: "Equity",
      content: `The Company shall authorize ${m(data,"total_shares")} total shares. Equity allocation:<br/>(a) ${m(data,"founder_1_name")}: ${m(data,"founder_1_equity_pct")}%<br/>(b) ${m(data,"founder_2_name")}: ${m(data,"founder_2_equity_pct")}%<br/>All shares are subject to the vesting schedule below.` },
    { id: "s4_heading", type: "heading", content: "4. Vesting Schedule" },
    { id: "s4_body", type: "paragraph", label: "Vesting",
      content: `Each Founder's equity shall vest over ${m(data,"vesting_years")} year(s) with a cliff of ${m(data,"cliff_months")} month(s). No shares vest before the cliff. After the cliff, shares vest monthly on a pro-rata basis. Unvested shares are forfeited upon departure.` },
    { id: "s5_heading", type: "heading", content: "5. Capital Contributions" },
    { id: "s5_body", type: "paragraph", label: "Capital",
      content: `Initial contributions:<br/>(a) ${m(data,"founder_1_name")}: ${m(data,"founder_1_capital")}<br/>(b) ${m(data,"founder_2_name")}: ${m(data,"founder_2_capital")}<br/>Additional contributions require unanimous written consent.` },
    { id: "s7_heading", type: "heading", content: "6. Decision-Making" },
    { id: "s7_body", type: "paragraph", label: "Governance",
      content: `Decisions shall be made by ${m(data,"decision_structure")} vote, except that equity issuance, debt over $10,000, sale/merger, agreement amendments, executive hiring, and related-party transactions require unanimous consent.` },
    { id: "s9_heading", type: "heading", content: "7. Non-Compete" },
    { id: "s9_body", type: "paragraph", label: "Non-Compete",
      content: `During the Agreement and for ${m(data,"non_compete_months")} month(s) after departure, each Founder agrees not to compete with the Company or solicit its employees, contractors, customers, or business partners.` },
    { id: "s12_heading", type: "heading", content: "8. Dispute Resolution" },
    { id: "s12_body", type: "paragraph", label: "Disputes",
      content: `Disputes shall be resolved by ${m(data,"dispute_resolution")} in ${m(data,"governing_law_jurisdiction")}. The prevailing party may recover reasonable attorneys' fees and costs.` },
    { id: "s13_heading", type: "heading", content: "9. Governing Law" },
    { id: "s13_body", type: "paragraph", label: "Governing Law",
      content: `This Agreement shall be governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "sig_heading", type: "heading", content: "10. Signatures" },
    { id: "sig_f1", type: "paragraph", label: "Founder 1 Signature",
      content: `<strong>Founder 1:</strong><br/>Name: ${m(data,"founder_1_name")}<br/>Title: ${m(data,"founder_1_title")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_f2", type: "paragraph", label: "Founder 2 Signature",
      content: `<strong>Founder 2:</strong><br/>Name: ${m(data,"founder_2_name")}<br/>Title: ${m(data,"founder_2_title")}<br/>Date: ${m(data,"signature_date")}` },
  ],

  ip_assignment: (data) => [
    { id: "header", type: "title", content: "INTELLECTUAL PROPERTY ASSIGNMENT AGREEMENT", editable: false },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This IP Assignment Agreement is entered into as of ${m(data,"effective_date")} by and between:` },
    { id: "s1_heading", type: "heading", content: "1. Parties" },
    { id: "s1_assignor", type: "paragraph", label: "Assignor",
      content: `<strong>Assignor:</strong> ${m(data,"assignor_name")}, ${m(data,"assignor_title")}, residing at ${m(data,"assignor_address")}.` },
    { id: "s1_assignee", type: "paragraph", label: "Assignee",
      content: `<strong>Assignee:</strong> ${m(data,"assignee_name")}, a ${m(data,"assignee_type")} organized under the laws of ${m(data,"assignee_jurisdiction")}, at ${m(data,"assignee_address")}.` },
    { id: "s3_heading", type: "heading", content: "2. Description of Intellectual Property" },
    { id: "s3_body", type: "paragraph", label: "IP Description",
      content: `The Assigned IP includes: ${m(data,"ip_description")}. This includes all patents, copyrights, trade secrets, trademarks, source code, documentation, designs, and all associated rights.` },
    { id: "s4_heading", type: "heading", content: "3. Assignment" },
    { id: "s4_body", type: "paragraph", label: "Assignment",
      content: `The Assignor hereby irrevocably assigns, transfers, and conveys to the Assignee all right, title, and interest in and to the Assigned IP, throughout the world, for the full term of such rights.` },
    { id: "s5_heading", type: "heading", content: "4. Consideration" },
    { id: "s5_body", type: "paragraph", label: "Consideration",
      content: `In consideration for the assignment: ${m(data,"consideration")}.` },
    { id: "s6_heading", type: "heading", content: "5. Representations and Warranties" },
    { id: "s6_body", type: "paragraph", label: "Warranties",
      content: `The Assignor represents and warrants: ${m(data,"warranty_scope")}. The Assignor is the sole owner of the Assigned IP, free of liens and encumbrances, and has full authority to make this assignment.` },
    { id: "s9_heading", type: "heading", content: "6. Governing Law" },
    { id: "s9_body", type: "paragraph", label: "Governing Law",
      content: `This Agreement shall be governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "sig_heading", type: "heading", content: "7. Signatures" },
    { id: "sig_assignor", type: "paragraph", label: "Assignor Signature",
      content: `<strong>Assignor:</strong><br/>Name: ${m(data,"assignor_signatory")}<br/>Title: ${m(data,"assignor_title")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_assignee", type: "paragraph", label: "Assignee Signature",
      content: `<strong>Assignee:</strong><br/>Company: ${m(data,"assignee_name")}<br/>Date: ${m(data,"signature_date")}` },
  ],

  service_agreement: (data) => [
    { id: "header", type: "title", content: "SERVICE AGREEMENT", editable: false },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This Service Agreement is entered into as of ${m(data,"effective_date")} by and between:` },
    { id: "s1_heading", type: "heading", content: "1. Parties" },
    { id: "s1_client", type: "paragraph", label: "Client",
      content: `<strong>Client:</strong> ${m(data,"client_name")}, a ${m(data,"client_type")} organized under the laws of ${m(data,"client_jurisdiction")}, at ${m(data,"client_address")}.` },
    { id: "s1_provider", type: "paragraph", label: "Provider",
      content: `<strong>Provider:</strong> ${m(data,"provider_name")}, a ${m(data,"provider_type")} organized under the laws of ${m(data,"provider_jurisdiction")}, at ${m(data,"provider_address")}.` },
    { id: "s2_heading", type: "heading", content: "2. Scope of Services" },
    { id: "s2_body", type: "paragraph", label: "Services",
      content: `The Provider shall perform: ${m(data,"service_description")}. Services shall be performed in a professional manner consistent with industry standards.` },
    { id: "s3_heading", type: "heading", content: "3. Deliverables" },
    { id: "s3_body", type: "paragraph", label: "Deliverables",
      content: `The Provider shall deliver: ${m(data,"deliverables")}. The Client has 15 business days to review and accept or reject each Deliverable.` },
    { id: "s4_heading", type: "heading", content: "4. Compensation" },
    { id: "s4_body", type: "paragraph", label: "Payment",
      content: `The Client shall pay ${m(data,"payment_amount")}, on a ${m(data,"payment_schedule")} basis. Invoices are due within 30 days of receipt. Late payments bear 1.5% monthly interest.` },
    { id: "s5_heading", type: "heading", content: "5. Term" },
    { id: "s5_body", type: "paragraph", label: "Term",
      content: `This Agreement commences on ${m(data,"term_start")} and continues until ${m(data,"term_end")}.` },
    { id: "s6_heading", type: "heading", content: "6. Termination" },
    { id: "s6_body", type: "paragraph", label: "Termination",
      content: `Either party may terminate with ${m(data,"termination_notice_days")} days' written notice. Immediate termination is permitted for material breach, insolvency, or cessation of business.` },
    { id: "s8_heading", type: "heading", content: "7. IP Ownership" },
    { id: "s8_body", type: "paragraph", label: "IP Ownership",
      content: `All IP in the Deliverables shall be owned by the ${m(data,"ip_ownership")}.` },
    { id: "s10_heading", type: "heading", content: "8. Limitation of Liability" },
    { id: "s10_body", type: "paragraph", label: "Liability Cap",
      content: `Total liability shall not exceed ${m(data,"liability_cap")}. Neither party is liable for indirect, incidental, special, or consequential damages.` },
    { id: "s11_heading", type: "heading", content: "9. Governing Law" },
    { id: "s11_body", type: "paragraph", label: "Governing Law",
      content: `This Agreement shall be governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "sig_heading", type: "heading", content: "10. Signatures" },
    { id: "sig_client", type: "paragraph", label: "Client Signature",
      content: `<strong>Client:</strong><br/>Company: ${m(data,"client_name")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_provider", type: "paragraph", label: "Provider Signature",
      content: `<strong>Provider:</strong><br/>Company: ${m(data,"provider_name")}<br/>Date: ${m(data,"signature_date")}` },
  ],

  contractor_agreement: (data) => [
    { id: "header", type: "title", content: "INDEPENDENT CONTRACTOR AGREEMENT", editable: false },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This Independent Contractor Agreement is entered into as of ${m(data,"effective_date")} by and between:` },
    { id: "s1_heading", type: "heading", content: "1. Parties" },
    { id: "s1_company", type: "paragraph", label: "Company",
      content: `<strong>Company:</strong> ${m(data,"company_name")}, at ${m(data,"company_address")}.` },
    { id: "s1_contractor", type: "paragraph", label: "Contractor",
      content: `<strong>Contractor:</strong> ${m(data,"contractor_name")}, at ${m(data,"contractor_address")}.` },
    { id: "s2_heading", type: "heading", content: "2. Scope of Work" },
    { id: "s2_body", type: "paragraph", label: "Scope",
      content: `The Contractor shall perform: ${m(data,"scope_of_work")}. The Contractor has sole discretion to determine the manner and means of performing the Services.` },
    { id: "s3_heading", type: "heading", content: "3. Compensation" },
    { id: "s3_body", type: "paragraph", label: "Compensation",
      content: `Rate: ${m(data,"compensation_amount")} (${m(data,"compensation_type")}). Payment terms: ${m(data,"payment_terms")}. The Contractor is solely responsible for all taxes.` },
    { id: "s4_heading", type: "heading", content: "4. Independent Contractor Status" },
    { id: "s4_body", type: "paragraph", label: "Status",
      content: `The Contractor is an independent contractor, not an employee. The Contractor is not entitled to benefits, workers' compensation, or unemployment insurance. The Company will issue Form 1099 as required by law.` },
    { id: "s5_heading", type: "heading", content: "5. Term" },
    { id: "s5_body", type: "paragraph", label: "Term",
      content: `Commences ${m(data,"term_start")}, continues until ${m(data,"term_end")}.` },
    { id: "s6_heading", type: "heading", content: "6. Termination" },
    { id: "s6_body", type: "paragraph", label: "Termination",
      content: `Either party may terminate with ${m(data,"termination_notice_days")} days' notice. Immediate termination for material breach.` },
    { id: "s8_heading", type: "heading", content: "7. IP Ownership" },
    { id: "s8_body", type: "paragraph", label: "IP",
      content: `All work product shall be owned by the ${m(data,"ip_ownership")}.` },
    { id: "s9_heading", type: "heading", content: "8. Non-Compete" },
    { id: "s9_body", type: "paragraph", label: "Non-Compete",
      content: `Non-compete period: ${m(data,"non_compete_months")} month(s) after termination.` },
    { id: "s10_heading", type: "heading", content: "9. Equipment" },
    { id: "s10_body", type: "paragraph", label: "Equipment",
      content: `Equipment provided by Company: ${m(data,"equipment_provided")}.` },
    { id: "s12_heading", type: "heading", content: "10. Governing Law" },
    { id: "s12_body", type: "paragraph", label: "Governing Law",
      content: `Governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "sig_heading", type: "heading", content: "11. Signatures" },
    { id: "sig_company", type: "paragraph", label: "Company Signature",
      content: `<strong>Company:</strong><br/>Company: ${m(data,"company_name")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_contractor", type: "paragraph", label: "Contractor Signature",
      content: `<strong>Contractor:</strong><br/>Name: ${m(data,"contractor_signatory")}<br/>Date: ${m(data,"signature_date")}` },
  ],

  safe: (data) => [
    { id: "header", type: "title", content: "SIMPLE AGREEMENT FOR FUTURE EQUITY (SAFE)", editable: false },
    { id: "disclaimer", type: "paragraph", label: "Securities Disclaimer",
      content: `<em>THIS INSTRUMENT AND ANY SECURITIES ISSUABLE PURSUANT HERETO HAVE NOT BEEN REGISTERED UNDER THE SECURITIES ACT OF 1933. THEY MAY NOT BE SOLD OR TRANSFERRED EXCEPT PURSUANT TO AN EFFECTIVE REGISTRATION STATEMENT OR AN EXEMPTION THEREFROM.</em>` },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This SAFE is entered into as of ${m(data,"effective_date")} by and between:` },
    { id: "s1_heading", type: "heading", content: "1. Parties" },
    { id: "s1_company", type: "paragraph", label: "Company",
      content: `<strong>Company:</strong> ${m(data,"company_name")}, a ${m(data,"company_type")} in ${m(data,"company_jurisdiction")}, at ${m(data,"company_address")}.` },
    { id: "s1_investor", type: "paragraph", label: "Investor",
      content: `<strong>Investor:</strong> ${m(data,"investor_name")}, at ${m(data,"investor_address")}.` },
    { id: "s2_heading", type: "heading", content: "2. Investment Amount" },
    { id: "s2_body", type: "paragraph", label: "Investment",
      content: `The Investor invests ${m(data,"investment_amount")} (the "Purchase Amount").` },
    { id: "s3_heading", type: "heading", content: "3. Conversion Events" },
    { id: "s3_equity", type: "paragraph", label: "Equity Financing",
      content: `<strong>Equity Financing:</strong> Upon qualified equity financing, the SAFE converts to preferred stock at the lower of: (a) price per share times the Discount Rate, or (b) Valuation Cap divided by Company Capitalization.` },
    { id: "s3_liquidity", type: "paragraph", label: "Liquidity Event",
      content: `<strong>Liquidity Event:</strong> The Investor may elect to receive cash equal to the Purchase Amount or convert to common stock at the Liquidity Price.` },
    { id: "s3_dissolution", type: "paragraph", label: "Dissolution",
      content: `<strong>Dissolution:</strong> The Investor receives a portion of assets equal to the Purchase Amount, senior to common stockholders.` },
    { id: "s4_heading", type: "heading", content: "4. Valuation Cap and Discount" },
    { id: "s4_body", type: "paragraph", label: "Terms",
      content: `Valuation Cap: ${m(data,"valuation_cap")}. Discount Rate: ${m(data,"discount_rate")}%. The Investor receives the more favorable conversion price.` },
    { id: "s5_heading", type: "heading", content: "5. Pro Rata Rights" },
    { id: "s5_body", type: "paragraph", label: "Pro Rata",
      content: `Pro rata rights: ${m(data,"pro_rata_rights")}. If granted, the Investor may participate in subsequent rounds on a pro rata basis.` },
    { id: "s6_heading", type: "heading", content: "6. Most Favored Nation" },
    { id: "s6_body", type: "paragraph", label: "MFN",
      content: `MFN clause: ${m(data,"mfn_clause")}. If applicable, the SAFE may be amended to match more favorable terms in subsequent SAFEs.` },
    { id: "s10_heading", type: "heading", content: "7. Governing Law" },
    { id: "s10_body", type: "paragraph", label: "Governing Law",
      content: `Governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "sig_heading", type: "heading", content: "8. Signatures" },
    { id: "sig_company", type: "paragraph", label: "Company Signature",
      content: `<strong>Company:</strong><br/>Company: ${m(data,"company_name")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_investor", type: "paragraph", label: "Investor Signature",
      content: `<strong>Investor:</strong><br/>Name: ${m(data,"investor_name")}<br/>Date: ${m(data,"signature_date")}` },
  ],

  advisory_agreement: (data) => [
    { id: "header", type: "title", content: "ADVISORY AGREEMENT", editable: false },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This Advisory Agreement is entered into as of ${m(data,"effective_date")} by and between:` },
    { id: "s1_heading", type: "heading", content: "1. Parties" },
    { id: "s1_company", type: "paragraph", label: "Company",
      content: `<strong>Company:</strong> ${m(data,"company_name")}, at ${m(data,"company_address")}.` },
    { id: "s1_advisor", type: "paragraph", label: "Advisor",
      content: `<strong>Advisor:</strong> ${m(data,"advisor_name")}, at ${m(data,"advisor_address")}.` },
    { id: "s2_heading", type: "heading", content: "2. Advisory Role" },
    { id: "s2_body", type: "paragraph", label: "Role",
      content: `The Advisor shall serve as ${m(data,"advisory_role")}. The Advisor acts in an advisory capacity only and has no authority to bind the Company.` },
    { id: "s3_heading", type: "heading", content: "3. Responsibilities" },
    { id: "s3_body", type: "paragraph", label: "Responsibilities",
      content: `The Advisor shall: ${m(data,"responsibilities")}.` },
    { id: "s4_heading", type: "heading", content: "4. Time Commitment" },
    { id: "s4_body", type: "paragraph", label: "Time",
      content: `The Advisor shall dedicate approximately ${m(data,"time_commitment")} to the Company.` },
    { id: "s5_heading", type: "heading", content: "5. Equity Compensation" },
    { id: "s5_body", type: "paragraph", label: "Equity",
      content: `The Advisor shall receive equity equal to ${m(data,"equity_percentage")} of fully diluted capitalization. No cash compensation unless otherwise agreed.` },
    { id: "s6_heading", type: "heading", content: "6. Vesting" },
    { id: "s6_body", type: "paragraph", label: "Vesting",
      content: `Equity vests over ${m(data,"vesting_months")} month(s) with a ${m(data,"cliff_months")} month cliff. Monthly vesting after the cliff.` },
    { id: "s7_heading", type: "heading", content: "7. Term" },
    { id: "s7_body", type: "paragraph", label: "Term",
      content: `This Agreement continues for ${m(data,"term_months")} month(s) from the Effective Date.` },
    { id: "s9_heading", type: "heading", content: "8. Confidentiality" },
    { id: "s9_body", type: "paragraph", label: "Confidentiality",
      content: `Confidentiality obligations survive for ${m(data,"confidentiality_term_years")} year(s) after termination.` },
    { id: "s12_heading", type: "heading", content: "9. Governing Law" },
    { id: "s12_body", type: "paragraph", label: "Governing Law",
      content: `Governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "sig_heading", type: "heading", content: "10. Signatures" },
    { id: "sig_company", type: "paragraph", label: "Company Signature",
      content: `<strong>Company:</strong><br/>Name: ${m(data,"company_signatory")}<br/>Company: ${m(data,"company_name")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_advisor", type: "paragraph", label: "Advisor Signature",
      content: `<strong>Advisor:</strong><br/>Name: ${m(data,"advisor_signatory")}<br/>Date: ${m(data,"signature_date")}` },
  ],

  employment_contract: (data) => [
    { id: "header", type: "title", content: "EMPLOYMENT CONTRACT", editable: false },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This Employment Contract is entered into as of ${m(data,"effective_date")} by and between:` },
    { id: "s1_heading", type: "heading", content: "1. Parties" },
    { id: "s1_employer", type: "paragraph", label: "Employer",
      content: `<strong>Employer:</strong> ${m(data,"company_name")}, at ${m(data,"company_address")}.` },
    { id: "s1_employee", type: "paragraph", label: "Employee",
      content: `<strong>Employee:</strong> ${m(data,"employee_name")}, at ${m(data,"employee_address")}.` },
    { id: "s2_heading", type: "heading", content: "2. Position and Duties" },
    { id: "s2_body", type: "paragraph", label: "Position",
      content: `Position: ${m(data,"position_title")} in ${m(data,"department")}, reporting to ${m(data,"reporting_to")}. Employment type: ${m(data,"employment_type")}. The Employee agrees to devote full working time to the Company.` },
    { id: "s3_heading", type: "heading", content: "3. Start Date" },
    { id: "s3_body", type: "paragraph", label: "Start Date",
      content: `Employment commences on ${m(data,"start_date")}, contingent upon background checks and employment eligibility verification.` },
    { id: "s4_heading", type: "heading", content: "4. Compensation" },
    { id: "s4_body", type: "paragraph", label: "Salary",
      content: `Base salary: ${m(data,"salary_amount")}, payable ${m(data,"salary_frequency")}. Subject to periodic review.` },
    { id: "s4_bonus", type: "paragraph", label: "Bonus",
      content: `<strong>Bonus:</strong> ${m(data,"bonus_structure")}` },
    { id: "s4_equity", type: "paragraph", label: "Equity",
      content: `<strong>Equity:</strong> ${m(data,"equity_grant")}` },
    { id: "s5_heading", type: "heading", content: "5. Benefits" },
    { id: "s5_body", type: "paragraph", label: "Benefits",
      content: `${m(data,"benefits_description")}` },
    { id: "s6_heading", type: "heading", content: "6. Vacation and PTO" },
    { id: "s6_body", type: "paragraph", label: "Vacation",
      content: `${m(data,"vacation_days")} days of paid vacation per year. Sick leave and holidays per Company policy.` },
    { id: "s7_heading", type: "heading", content: "7. Probation Period" },
    { id: "s7_body", type: "paragraph", label: "Probation",
      content: `Probation period: ${m(data,"probation_months")} month(s). During probation, either party may terminate with 1 week's notice.` },
    { id: "s8_heading", type: "heading", content: "8. Work Location" },
    { id: "s8_body", type: "paragraph", label: "Location",
      content: `Primary location: ${m(data,"work_location")}. Remote policy: ${m(data,"remote_policy")}.` },
    { id: "s9_heading", type: "heading", content: "9. Termination" },
    { id: "s9_body", type: "paragraph", label: "Termination",
      content: `After probation, either party may terminate with ${m(data,"termination_notice_days")} days' notice. Immediate termination for Cause (breach, fraud, misconduct, gross negligence, etc.).` },
    { id: "s13_heading", type: "heading", content: "10. Governing Law" },
    { id: "s13_body", type: "paragraph", label: "Governing Law",
      content: `Governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "sig_heading", type: "heading", content: "11. Signatures" },
    { id: "sig_employer", type: "paragraph", label: "Employer Signature",
      content: `<strong>Employer:</strong><br/>Name: ${m(data,"company_signatory")}<br/>Company: ${m(data,"company_name")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_employee", type: "paragraph", label: "Employee Signature",
      content: `<strong>Employee:</strong><br/>Name: ${m(data,"employee_name")}<br/>Date: ${m(data,"signature_date")}` },
  ],

  employee_nda: (data) => [
    { id: "header", type: "title", content: "EMPLOYEE CONFIDENTIALITY AND NON-DISCLOSURE AGREEMENT", editable: false },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This Employee NDA is entered into as of ${m(data,"effective_date")} by and between:` },
    { id: "s1_heading", type: "heading", content: "1. Parties" },
    { id: "s1_company", type: "paragraph", label: "Company",
      content: `<strong>Company:</strong> ${m(data,"company_name")}, at ${m(data,"company_address")}.` },
    { id: "s1_employee", type: "paragraph", label: "Employee",
      content: `<strong>Employee:</strong> ${m(data,"employee_name")}, ${m(data,"employee_title")}.` },
    { id: "s2_heading", type: "heading", content: "2. Definition of Confidential Information" },
    { id: "s2_body", type: "paragraph", label: "Confidential Info",
      content: `Confidential Information includes: ${m(data,"confidential_info_description")}. This also includes any information a reasonable person would understand to be confidential.` },
    { id: "s3_heading", type: "heading", content: "3. Exclusions" },
    { id: "s3_body", type: "paragraph", label: "Exclusions",
      content: `Excluded from confidentiality: ${m(data,"exclusions")}. Also excluded: publicly available information, prior lawful possession, independent development, and legally compelled disclosures.` },
    { id: "s4_heading", type: "heading", content: "4. Employee Obligations" },
    { id: "s4_body", type: "paragraph", label: "Obligations",
      content: `The Employee shall: (a) hold all information in strict confidence; (b) use it solely for Company duties; (c) take reasonable precautions; (d) not copy except as necessary; (e) notify Company of unauthorized disclosure; (f) comply with all Company security policies.` },
    { id: "s6_heading", type: "heading", content: "5. Non-Solicitation" },
    { id: "s6_body", type: "paragraph", label: "Non-Solicitation",
      content: `Non-solicitation period: ${m(data,"non_solicitation_months")} month(s) post-employment. The Employee shall not solicit employees, contractors, customers, or business partners.` },
    { id: "s7_heading", type: "heading", content: "6. Return of Materials" },
    { id: "s7_body", type: "paragraph", label: "Return",
      content: `Within ${m(data,"return_of_materials_days")} day(s) of termination, the Employee shall return all Company materials and permanently delete electronic copies.` },
    { id: "s8_heading", type: "heading", content: "7. Remedies" },
    { id: "s8_body", type: "paragraph", label: "Remedies",
      content: `${m(data,"remedy_description")}. The Company may seek injunctive relief and attorneys' fees.` },
    { id: "s9_heading", type: "heading", content: "8. Duration" },
    { id: "s9_body", type: "paragraph", label: "Duration",
      content: `Obligations last ${m(data,"obligations_duration_years")} year(s) post-employment. Trade secret obligations continue as long as the information retains trade secret status.` },
    { id: "s10_heading", type: "heading", content: "9. Governing Law" },
    { id: "s10_body", type: "paragraph", label: "Governing Law",
      content: `Governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "sig_heading", type: "heading", content: "10. Signatures" },
    { id: "sig_company", type: "paragraph", label: "Company Signature",
      content: `<strong>Company:</strong><br/>Name: ${m(data,"company_signatory")}<br/>Company: ${m(data,"company_name")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_employee", type: "paragraph", label: "Employee Signature",
      content: `<strong>Employee:</strong><br/>Name: ${m(data,"employee_name")}<br/>Title: ${m(data,"employee_title")}<br/>Date: ${m(data,"signature_date")}` },
  ],

  invention_assignment: (data) => [
    { id: "header", type: "title", content: "EMPLOYEE INVENTION ASSIGNMENT AGREEMENT", editable: false },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This Invention Assignment Agreement is entered into as of ${m(data,"effective_date")} by and between:` },
    { id: "s1_heading", type: "heading", content: "1. Parties" },
    { id: "s1_company", type: "paragraph", label: "Company",
      content: `<strong>Company:</strong> ${m(data,"company_name")}, at ${m(data,"company_address")}.` },
    { id: "s1_employee", type: "paragraph", label: "Employee",
      content: `<strong>Employee:</strong> ${m(data,"employee_name")}, ${m(data,"employee_title")}.` },
    { id: "s3_heading", type: "heading", content: "2. Scope of Inventions" },
    { id: "s3_body", type: "paragraph", label: "Scope",
      content: `This Agreement covers: ${m(data,"scope_of_inventions")}.` },
    { id: "s4_heading", type: "heading", content: "3. Assignment of Inventions" },
    { id: "s4_body", type: "paragraph", label: "Assignment",
      content: `The Employee irrevocably assigns all Company Inventions to the Company, including all IP rights, throughout the world, for the full term of such rights.` },
    { id: "s5_heading", type: "heading", content: "4. Prior Inventions (Schedule A)" },
    { id: "s5_body", type: "paragraph", label: "Prior Inventions",
      content: `Excluded prior inventions: ${m(data,"prior_inventions")}. The Employee shall not incorporate prior inventions into Company work without written consent.` },
    { id: "s6_heading", type: "heading", content: "5. Disclosure Obligation" },
    { id: "s6_body", type: "paragraph", label: "Disclosure",
      content: `Disclosure requirements: ${m(data,"disclosure_requirements")}.` },
    { id: "s7_heading", type: "heading", content: "6. Works Made for Hire" },
    { id: "s7_body", type: "paragraph", label: "Works for Hire",
      content: `Works made for hire: ${m(data,"works_for_hire")}. If applicable, the Company is the sole author; otherwise, the Employee assigns all rights.` },
    { id: "s8_heading", type: "heading", content: "7. Moral Rights" },
    { id: "s8_body", type: "paragraph", label: "Moral Rights",
      content: `Moral rights waiver: ${m(data,"moral_rights_waiver")}. The Employee consents to use, modification, and distribution without attribution.` },
    { id: "s10_heading", type: "heading", content: "8. Governing Law" },
    { id: "s10_body", type: "paragraph", label: "Governing Law",
      content: `Governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "sig_heading", type: "heading", content: "9. Signatures" },
    { id: "sig_company", type: "paragraph", label: "Company Signature",
      content: `<strong>Company:</strong><br/>Name: ${m(data,"company_signatory")}<br/>Company: ${m(data,"company_name")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_employee", type: "paragraph", label: "Employee Signature",
      content: `<strong>Employee:</strong><br/>Name: ${m(data,"employee_signatory")}<br/>Title: ${m(data,"employee_title")}<br/>Date: ${m(data,"signature_date")}` },
  ],

  at_will_employment: (data) => [
    { id: "header", type: "title", content: "AT-WILL EMPLOYMENT AGREEMENT", editable: false },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This At-Will Employment Agreement is entered into as of ${m(data,"effective_date")} by and between:` },
    { id: "s1_heading", type: "heading", content: "1. Parties" },
    { id: "s1_employer", type: "paragraph", label: "Employer",
      content: `<strong>Employer:</strong> ${m(data,"company_name")}, at ${m(data,"company_address")}.` },
    { id: "s1_employee", type: "paragraph", label: "Employee",
      content: `<strong>Employee:</strong> ${m(data,"employee_name")}.` },
    { id: "s2_heading", type: "heading", content: "2. At-Will Employment" },
    { id: "s2_body", type: "paragraph", label: "At-Will Statement",
      content: `Employment is at-will. Either party may terminate at any time, for any reason, with or without cause or notice. The at-will nature cannot be changed except by written agreement signed by an authorized officer.` },
    { id: "s2_notice", type: "paragraph", label: "Notice Period",
      content: `Courtesy notice period: ${m(data,"at_will_notice_period")}.` },
    { id: "s3_heading", type: "heading", content: "3. Position" },
    { id: "s3_body", type: "paragraph", label: "Position",
      content: `Position: ${m(data,"position_title")}, commencing ${m(data,"start_date")}. Duties may be modified at the Company's discretion.` },
    { id: "s4_heading", type: "heading", content: "4. Compensation" },
    { id: "s4_body", type: "paragraph", label: "Salary",
      content: `Salary: ${m(data,"salary_amount")}. Subject to periodic review. Salary increases do not alter the at-will nature.` },
    { id: "s5_heading", type: "heading", content: "5. Employee Handbook" },
    { id: "s5_body", type: "paragraph", label: "Handbook",
      content: `Handbook acknowledgment: ${m(data,"handbook_acknowledgment")}. The handbook is not a contract and does not create contractual rights.` },
    { id: "s11_heading", type: "heading", content: "6. Governing Law" },
    { id: "s11_body", type: "paragraph", label: "Governing Law",
      content: `Governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "sig_heading", type: "heading", content: "7. Signatures" },
    { id: "sig_employer", type: "paragraph", label: "Employer Signature",
      content: `<strong>Employer:</strong><br/>Name: ${m(data,"company_signatory")}<br/>Company: ${m(data,"company_name")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_employee", type: "paragraph", label: "Employee Signature",
      content: `<strong>Employee:</strong><br/>Name: ${m(data,"employee_name")}<br/>Date: ${m(data,"signature_date")}` },
  ],

  non_compete: (data) => [
    { id: "header", type: "title", content: "NON-COMPETE AND NON-SOLICITATION AGREEMENT", editable: false },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This Non-Compete Agreement is entered into as of ${m(data,"effective_date")} by and between:` },
    { id: "s1_heading", type: "heading", content: "1. Parties" },
    { id: "s1_company", type: "paragraph", label: "Company",
      content: `<strong>Company:</strong> ${m(data,"company_name")}, at ${m(data,"company_address")}.` },
    { id: "s1_employee", type: "paragraph", label: "Employee",
      content: `<strong>Employee:</strong> ${m(data,"employee_name")}, ${m(data,"employee_title")}.` },
    { id: "s3_heading", type: "heading", content: "2. Non-Compete Covenant" },
    { id: "s3_body", type: "paragraph", label: "Non-Compete",
      content: `During employment and for ${m(data,"non_compete_months")} month(s) after termination, the Employee shall not engage in, own, manage, or participate in any competing business.` },
    { id: "s4_heading", type: "heading", content: "3. Geographic Scope" },
    { id: "s4_body", type: "paragraph", label: "Geography",
      content: `Geographic scope: ${m(data,"geographic_scope")}.` },
    { id: "s5_heading", type: "heading", content: "4. Restricted Activities" },
    { id: "s5_body", type: "paragraph", label: "Restrictions",
      content: `${m(data,"restricted_activities")}` },
    { id: "s6_heading", type: "heading", content: "5. Non-Solicitation of Customers" },
    { id: "s6_body", type: "paragraph", label: "Customer Non-Solicitation",
      content: `For ${m(data,"non_solicitation_months")} month(s) after termination, the Employee shall not solicit any customer or client of the Company.` },
    { id: "s7_heading", type: "heading", content: "6. Non-Solicitation of Employees" },
    { id: "s7_body", type: "paragraph", label: "Employee Non-Solicitation",
      content: `Scope: ${m(data,"non_solicitation_scope")}. The Employee shall not recruit, solicit, or hire any Company employee or contractor.` },
    { id: "s8_heading", type: "heading", content: "7. Consideration" },
    { id: "s8_body", type: "paragraph", label: "Consideration",
      content: `Consideration: ${m(data,"consideration")}.` },
    { id: "s9_heading", type: "heading", content: "8. Garden Leave" },
    { id: "s9_body", type: "paragraph", label: "Garden Leave",
      content: `Garden leave: ${m(data,"garden_leave_months")} month(s). During this period, the Employee may be required to remain away from the workplace while receiving full compensation.` },
    { id: "s11_heading", type: "heading", content: "9. Remedies" },
    { id: "s11_body", type: "paragraph", label: "Enforcement",
      content: `Enforcement mechanism: ${m(data,"enforcement_mechanism")}. Breach extends the Restricted Period by the duration of the breach.` },
    { id: "s13_heading", type: "heading", content: "10. Governing Law" },
    { id: "s13_body", type: "paragraph", label: "Governing Law",
      content: `Governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "sig_heading", type: "heading", content: "11. Signatures" },
    { id: "sig_company", type: "paragraph", label: "Company Signature",
      content: `<strong>Company:</strong><br/>Name: ${m(data,"company_signatory")}<br/>Company: ${m(data,"company_name")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_employee", type: "paragraph", label: "Employee Signature",
      content: `<strong>Employee:</strong><br/>Name: ${m(data,"employee_name")}<br/>Title: ${m(data,"employee_title")}<br/>Date: ${m(data,"signature_date")}` },
  ],

  privacy_policy: (data) => [
    { id: "header", type: "title", content: "PRIVACY POLICY", editable: false },
    { id: "meta", type: "paragraph", label: "Dates",
      content: `Last Updated: ${m(data,"last_updated")}<br/>Effective Date: ${m(data,"effective_date")}` },
    { id: "s1_heading", type: "heading", content: "1. Introduction" },
    { id: "s1_body", type: "paragraph", label: "Introduction",
      content: `${m(data,"company_name")}, located at ${m(data,"company_address")}, operates ${m(data,"website_url")}. This Privacy Policy explains how we collect, use, disclose, and safeguard your personal information.` },
    { id: "s2_heading", type: "heading", content: "2. Information We Collect" },
    { id: "s2_body", type: "paragraph", label: "Data Collected",
      content: `We collect: ${m(data,"data_collected")}. Information may be collected directly, automatically (IP, browser, device data), or from third-party sources.` },
    { id: "s3_heading", type: "heading", content: "3. How We Use Your Information" },
    { id: "s3_body", type: "paragraph", label: "Data Usage",
      content: `We use your information for: ${m(data,"data_usage")}. Additionally: providing the Service, communicating about your account, marketing (with consent), fraud prevention, legal compliance, and research.` },
    { id: "s4_heading", type: "heading", content: "4. Information Sharing" },
    { id: "s4_body", type: "paragraph", label: "Sharing",
      content: `We share data with: ${m(data,"data_sharing")}. Also with service providers, legal authorities, in M&A transactions, and with your consent.` },
    { id: "s5_heading", type: "heading", content: "5. Data Retention" },
    { id: "s5_body", type: "paragraph", label: "Retention",
      content: `Retention period: ${m(data,"data_retention_period")}. Data is securely deleted or anonymized when no longer needed.` },
    { id: "s6_heading", type: "heading", content: "6. Cookies and Tracking" },
    { id: "s6_body", type: "paragraph", label: "Cookies",
      content: `${m(data,"cookie_usage")}. Types: strictly necessary, performance, functionality, and targeting cookies (if applicable).` },
    { id: "s7_heading", type: "heading", content: "7. Your Rights" },
    { id: "s7_body", type: "paragraph", label: "User Rights",
      content: `${m(data,"user_rights")}. Depending on jurisdiction: access, correction, deletion, restriction, portability, consent withdrawal, and complaint rights. Contact: ${m(data,"contact_email")}.` },
    { id: "s8_heading", type: "heading", content: "8. Children's Privacy" },
    { id: "s8_body", type: "paragraph", label: "Children",
      content: `Policy: ${m(data,"children_policy")}. The Service is not intended for children under 13. Contact ${m(data,"contact_email")} if you believe a child has provided personal information.` },
    { id: "s12_heading", type: "heading", content: "9. Contact Information" },
    { id: "s12_body", type: "paragraph", label: "Contact",
      content: `${m(data,"company_name")}<br/>${m(data,"company_address")}<br/>Email: ${m(data,"contact_email")}<br/>DPO: ${m(data,"dpo_contact")}` },
  ],

  terms_of_service: (data) => [
    { id: "header", type: "title", content: "TERMS OF SERVICE", editable: false },
    { id: "meta", type: "paragraph", label: "Dates",
      content: `Last Updated: ${m(data,"last_updated")}<br/>Effective Date: ${m(data,"effective_date")}` },
    { id: "s1_heading", type: "heading", content: "1. Acceptance of Terms" },
    { id: "s1_body", type: "paragraph", label: "Acceptance",
      content: `${m(data,"company_name")}, at ${m(data,"company_address")}, provides ${m(data,"website_url")}. By using the Service, you agree to these Terms.` },
    { id: "s2_heading", type: "heading", content: "2. Eligibility" },
    { id: "s2_body", type: "paragraph", label: "Eligibility",
      content: `Minimum age: ${m(data,"eligibility_age")} years. You represent that you meet this requirement and have legal capacity.` },
    { id: "s4_heading", type: "heading", content: "3. Service Description" },
    { id: "s4_body", type: "paragraph", label: "Service",
      content: `${m(data,"service_description")}. We may modify or discontinue the Service at any time.` },
    { id: "s5_heading", type: "heading", content: "4. Acceptable Use" },
    { id: "s5_body", type: "paragraph", label: "Acceptable Use",
      content: `${m(data,"acceptable_use")}. You shall not violate laws, interfere with the Service, transmit malware, or use automated access without consent.` },
    { id: "s6_heading", type: "heading", content: "5. User Content" },
    { id: "s6_body", type: "paragraph", label: "User Content",
      content: `Content rights: ${m(data,"user_content_rights")}. You are responsible for your content and warrant it does not violate third-party rights.` },
    { id: "s8_heading", type: "heading", content: "6. Payment and Billing" },
    { id: "s8_body", type: "paragraph", label: "Billing",
      content: `${m(data,"subscription_terms")}. Fees are non-refundable unless stated otherwise. You are responsible for applicable taxes.` },
    { id: "s9_heading", type: "heading", content: "7. Termination" },
    { id: "s9_body", type: "paragraph", label: "Termination",
      content: `${m(data,"termination_conditions")}. We may suspend or terminate your access for any reason. Surviving provisions remain in effect.` },
    { id: "s10_heading", type: "heading", content: "8. Disclaimers" },
    { id: "s10_body", type: "paragraph", label: "Disclaimers",
      content: `THE SERVICE IS PROVIDED "AS IS." ${m(data,"warranty_disclaimer")}. We disclaim all warranties of merchantability, fitness, and non-infringement.` },
    { id: "s11_heading", type: "heading", content: "9. Limitation of Liability" },
    { id: "s11_body", type: "paragraph", label: "Liability",
      content: `Maximum liability: ${m(data,"liability_cap")}. No liability for indirect, incidental, special, or consequential damages.` },
    { id: "s13_heading", type: "heading", content: "10. Dispute Resolution" },
    { id: "s13_body", type: "paragraph", label: "Disputes",
      content: `Disputes resolved by ${m(data,"dispute_resolution")}. Prevailing party may recover attorneys' fees.` },
    { id: "s14_heading", type: "heading", content: "11. Governing Law" },
    { id: "s14_body", type: "paragraph", label: "Governing Law",
      content: `Governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "s16_heading", type: "heading", content: "12. Contact" },
    { id: "s16_body", type: "paragraph", label: "Contact",
      content: `${m(data,"company_name")}<br/>${m(data,"company_address")}<br/>Email: ${m(data,"contact_email")}` },
  ],

  termination_letter: (data) => [
    { id: "header", type: "title", content: "EMPLOYEE TERMINATION / LAYOFF LETTER", editable: false },
    { id: "date_block", type: "paragraph", label: "Letter Date",
      content: `Date: ${m(data,"letter_date")}<br/>${m(data,"company_name")}<br/>${m(data,"company_address")}` },
    { id: "recipient", type: "paragraph", label: "Recipient",
      content: `To: ${m(data,"employee_name")}, ${m(data,"employee_title")}<br/>${m(data,"employee_address")}` },
    { id: "s1_heading", type: "heading", content: "1. Notice of Termination" },
    { id: "s1_body", type: "paragraph", label: "Termination Notice",
      content: `Dear ${m(data,"employee_name")},<br/><br/>This letter serves as formal notification that your employment with ${m(data,"company_name")} will be terminated effective ${m(data,"termination_date")}. We are committed to supporting you through this transition.` },
    { id: "s2_heading", type: "heading", content: "2. Reason for Termination" },
    { id: "s2_body", type: "paragraph", label: "Reason",
      content: `Reason: ${m(data,"reason_for_termination")}. This decision was made after careful consideration and is not a reflection of your personal qualities.` },
    { id: "s3_heading", type: "heading", content: "3. Final Compensation" },
    { id: "s3_body", type: "paragraph", label: "Final Pay",
      content: `Your final paycheck will be issued on ${m(data,"final_paycheck_date")}, including all earned wages and accrued unused PTO.` },
    { id: "s4_heading", type: "heading", content: "4. Severance" },
    { id: "s4_body", type: "paragraph", label: "Severance",
      content: `Severance offered: ${m(data,"severance_offered")}. ${m(data,"severance_details")}` },
    { id: "s5_heading", type: "heading", content: "5. Benefits Continuation" },
    { id: "s5_body", type: "paragraph", label: "Benefits",
      content: `Benefits remain in effect through ${m(data,"benefits_end_date")}. COBRA eligible: ${m(data,"cobra_eligible")}. Separate COBRA notification with enrollment details will be sent.` },
    { id: "s6_heading", type: "heading", content: "6. Return of Company Property" },
    { id: "s6_body", type: "paragraph", label: "Property Return",
      content: `All Company property must be returned by ${m(data,"return_of_property_date")} including: laptop, phone, ID badges, keys, credit cards, documents, and all other Company materials.` },
    { id: "s9_heading", type: "heading", content: "7. Contact Information" },
    { id: "s9_body", type: "paragraph", label: "Contact",
      content: `For questions, contact: ${m(data,"contact_person")}.` },
    { id: "closing", type: "paragraph", label: "Closing",
      content: `We wish you the best in your future endeavors.<br/><br/>Sincerely,<br/>${m(data,"company_signatory")}<br/>${m(data,"manager_name")}, ${m(data,"manager_title")}<br/>${m(data,"company_name")}` },
  ],

  severance_agreement: (data) => [
    { id: "header", type: "title", content: "SEVERANCE AND SEPARATION AGREEMENT", editable: false },
    { id: "preamble", type: "paragraph", label: "Preamble",
      content: `This Severance Agreement is entered into as of ${m(data,"effective_date")} by and between:` },
    { id: "s1_heading", type: "heading", content: "1. Parties" },
    { id: "s1_company", type: "paragraph", label: "Company",
      content: `<strong>Company:</strong> ${m(data,"company_name")}, at ${m(data,"company_address")}.` },
    { id: "s1_employee", type: "paragraph", label: "Employee",
      content: `<strong>Employee:</strong> ${m(data,"employee_name")}, at ${m(data,"employee_address")}, most recently ${m(data,"employee_title")}.` },
    { id: "s3_heading", type: "heading", content: "2. Separation Date" },
    { id: "s3_body", type: "paragraph", label: "Separation",
      content: `Last day of employment: ${m(data,"termination_date")}. The Employee shall have no authority to act on behalf of the Company after this date.` },
    { id: "s4_heading", type: "heading", content: "3. Severance Payment" },
    { id: "s4_body", type: "paragraph", label: "Severance",
      content: `Severance: ${m(data,"severance_amount")}, payable ${m(data,"severance_schedule")} over ${m(data,"severance_duration_months")} month(s). Subject to applicable withholdings. First payment after the revocation period expires.` },
    { id: "s5_heading", type: "heading", content: "4. Benefits Continuation" },
    { id: "s5_body", type: "paragraph", label: "Benefits",
      content: `Health insurance continues at Company expense for ${m(data,"benefits_continuation_months")} month(s). COBRA available at Employee's expense after that period.` },
    { id: "s6_heading", type: "heading", content: "5. Equity Treatment" },
    { id: "s6_body", type: "paragraph", label: "Equity",
      content: `${m(data,"equity_treatment")}. Unvested equity forfeited as of the Separation Date unless otherwise specified.` },
    { id: "s7_heading", type: "heading", content: "6. Outplacement Services" },
    { id: "s7_body", type: "paragraph", label: "Outplacement",
      content: `Outplacement services: ${m(data,"outplacement_services")}.` },
    { id: "s8_heading", type: "heading", content: "7. General Release of Claims" },
    { id: "s8_body", type: "paragraph", label: "Release",
      content: `The Employee releases the Company and its affiliates from all claims arising from employment or separation, including claims under Title VII, ADA, ADEA, FMLA, ERISA, and all state/local laws.` },
    { id: "s10_heading", type: "heading", content: "8. Non-Disparagement" },
    { id: "s10_body", type: "paragraph", label: "Non-Disparagement",
      content: `Non-disparagement: ${m(data,"non_disparagement")}. Does not prohibit truthful testimony or statements to government agencies.` },
    { id: "s11_heading", type: "heading", content: "9. Non-Compete" },
    { id: "s11_body", type: "paragraph", label: "Non-Compete",
      content: `Post-separation non-compete: ${m(data,"non_compete_months")} month(s). The Employee shall not compete with or solicit employees/customers of the Company.` },
    { id: "s14_heading", type: "heading", content: "10. Reference" },
    { id: "s14_body", type: "paragraph", label: "Reference",
      content: `Reference policy: ${m(data,"reference_policy")}.` },
    { id: "s16_heading", type: "heading", content: "11. Consideration Period" },
    { id: "s16_body", type: "paragraph", label: "Consideration",
      content: `The Employee has ${m(data,"consideration_period_days")} day(s) to review and consider this Agreement. Consultation with an attorney is advised.` },
    { id: "s17_heading", type: "heading", content: "12. Revocation Period" },
    { id: "s17_body", type: "paragraph", label: "Revocation",
      content: `The Employee has ${m(data,"revocation_period_days")} day(s) after signing to revoke. Revocation must be in writing. The Agreement is not effective until the revocation period expires.` },
    { id: "s19_heading", type: "heading", content: "13. Governing Law" },
    { id: "s19_body", type: "paragraph", label: "Governing Law",
      content: `Governed by the laws of ${m(data,"governing_law_jurisdiction")}.` },
    { id: "sig_heading", type: "heading", content: "14. Signatures" },
    { id: "sig_company", type: "paragraph", label: "Company Signature",
      content: `<strong>Company:</strong><br/>Name: ${m(data,"company_signatory")}<br/>Company: ${m(data,"company_name")}<br/>Date: ${m(data,"signature_date")}` },
    { id: "sig_employee", type: "paragraph", label: "Employee Signature",
      content: `<strong>Employee:</strong><br/>Name: ${m(data,"employee_name")}<br/>Date: ${m(data,"signature_date")}` },
  ],
};

export function buildEditorSections(
  template: LegalTemplate,
  data: Record<string, string>
): EditorSection[] {
  const builder = SECTION_BUILDERS[template.id];
  if (builder) return builder(data);

  return [
    {
      id: "content",
      type: "paragraph",
      label: "Document Content",
      content:
        "Template section builder not implemented for this template type.",
    },
  ];
}
