export interface TemplateField {
  key: string;
  label: string;
  type: "text" | "textarea" | "date" | "number" | "select";
  required: boolean;
  options?: string[];
}

export interface LegalTemplate {
  id: string;
  name: string;
  file: string;
  description: string;
  fields: TemplateField[];
}

export const TEMPLATE_REGISTRY: Record<string, LegalTemplate> = {
  // ═══════════════════════════════════════════════════════════
  //  STAGE 1: FORMATION & FOUNDERS
  // ═══════════════════════════════════════════════════════════

  nda: {
    id: "nda",
    name: "Non-Disclosure Agreement",
    file: "templates/nda-template.docx",
    description: "Standard one-way or mutual NDA for business relationships",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "disclosing_party_name", label: "Disclosing Party Name", type: "text", required: true },
      { key: "disclosing_party_type", label: "Disclosing Party Entity Type", type: "select", required: true, options: ["corporation", "LLC", "partnership", "individual"] },
      { key: "disclosing_party_jurisdiction", label: "Disclosing Party Jurisdiction", type: "text", required: true },
      { key: "disclosing_party_address", label: "Disclosing Party Address", type: "text", required: true },
      { key: "receiving_party_name", label: "Receiving Party Name", type: "text", required: true },
      { key: "receiving_party_type", label: "Receiving Party Entity Type", type: "select", required: true, options: ["corporation", "LLC", "partnership", "individual"] },
      { key: "receiving_party_jurisdiction", label: "Receiving Party Jurisdiction", type: "text", required: true },
      { key: "receiving_party_address", label: "Receiving Party Address", type: "text", required: true },
      { key: "purpose", label: "Purpose of Disclosure", type: "textarea", required: true },
      { key: "confidential_info_description", label: "Confidential Information Description", type: "textarea", required: true },
      { key: "term_years", label: "Agreement Term (years)", type: "number", required: true },
      { key: "notice_days", label: "Termination Notice (days)", type: "number", required: true },
      { key: "survival_years", label: "Survival Period (years)", type: "number", required: true },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "disclosing_party_signatory", label: "Disclosing Party Signatory", type: "text", required: true },
      { key: "disclosing_party_signatory_title", label: "Disclosing Signatory Title", type: "text", required: true },
      { key: "receiving_party_signatory", label: "Receiving Party Signatory", type: "text", required: true },
      { key: "receiving_party_signatory_title", label: "Receiving Signatory Title", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },

  founders_agreement: {
    id: "founders_agreement",
    name: "Founders Agreement",
    file: "templates/founders-agreement-template.docx",
    description: "Equity splits, roles, vesting, decision-making, and dissolution among co-founders",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "company_name", label: "Company Legal Name", type: "text", required: true },
      { key: "company_type", label: "Entity Type", type: "select", required: true, options: ["corporation", "LLC", "partnership"] },
      { key: "company_jurisdiction", label: "State of Incorporation", type: "text", required: true },
      { key: "company_address", label: "Principal Office Address", type: "text", required: true },
      { key: "business_description", label: "Business Description", type: "textarea", required: true },
      { key: "founder_1_name", label: "Founder 1 Name", type: "text", required: true },
      { key: "founder_1_title", label: "Founder 1 Title", type: "text", required: true },
      { key: "founder_1_equity_pct", label: "Founder 1 Equity (%)", type: "number", required: true },
      { key: "founder_1_capital", label: "Founder 1 Capital Contribution", type: "text", required: true },
      { key: "founder_2_name", label: "Founder 2 Name", type: "text", required: true },
      { key: "founder_2_title", label: "Founder 2 Title", type: "text", required: true },
      { key: "founder_2_equity_pct", label: "Founder 2 Equity (%)", type: "number", required: true },
      { key: "founder_2_capital", label: "Founder 2 Capital Contribution", type: "text", required: true },
      { key: "total_shares", label: "Total Authorized Shares", type: "number", required: true },
      { key: "vesting_years", label: "Vesting Period (years)", type: "number", required: true },
      { key: "cliff_months", label: "Cliff Period (months)", type: "number", required: true },
      { key: "decision_structure", label: "Decision-Making Structure", type: "select", required: true, options: ["majority", "unanimous", "board"] },
      { key: "non_compete_months", label: "Non-Compete Period (months)", type: "number", required: true },
      { key: "dispute_resolution", label: "Dispute Resolution Method", type: "select", required: true, options: ["arbitration", "mediation", "litigation"] },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },

  ip_assignment: {
    id: "ip_assignment",
    name: "IP Assignment Agreement",
    file: "templates/ip-assignment-template.docx",
    description: "Assigns pre-existing intellectual property from a founder or employee to the company",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "assignor_name", label: "Assignor Name", type: "text", required: true },
      { key: "assignor_title", label: "Assignor Title", type: "text", required: true },
      { key: "assignor_address", label: "Assignor Address", type: "text", required: true },
      { key: "assignee_name", label: "Assignee (Company) Name", type: "text", required: true },
      { key: "assignee_type", label: "Company Entity Type", type: "select", required: true, options: ["corporation", "LLC", "partnership"] },
      { key: "assignee_jurisdiction", label: "Company Jurisdiction", type: "text", required: true },
      { key: "assignee_address", label: "Company Address", type: "text", required: true },
      { key: "ip_description", label: "Description of IP", type: "textarea", required: true },
      { key: "consideration", label: "Consideration / Compensation", type: "text", required: true },
      { key: "warranty_scope", label: "Representations & Warranties", type: "textarea", required: true },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "assignor_signatory", label: "Assignor Signatory Name", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  //  STAGE 2: BUSINESS OPERATIONS & PARTNERSHIPS
  // ═══════════════════════════════════════════════════════════

  service_agreement: {
    id: "service_agreement",
    name: "Service Agreement",
    file: "templates/service-agreement-template.docx",
    description: "Engaging vendors or service providers for defined work with payment terms and IP ownership",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "client_name", label: "Client Name", type: "text", required: true },
      { key: "client_type", label: "Client Entity Type", type: "select", required: true, options: ["corporation", "LLC", "partnership", "individual"] },
      { key: "client_jurisdiction", label: "Client Jurisdiction", type: "text", required: true },
      { key: "client_address", label: "Client Address", type: "text", required: true },
      { key: "provider_name", label: "Service Provider Name", type: "text", required: true },
      { key: "provider_type", label: "Provider Entity Type", type: "select", required: true, options: ["corporation", "LLC", "partnership", "individual"] },
      { key: "provider_jurisdiction", label: "Provider Jurisdiction", type: "text", required: true },
      { key: "provider_address", label: "Provider Address", type: "text", required: true },
      { key: "service_description", label: "Scope of Services", type: "textarea", required: true },
      { key: "deliverables", label: "Deliverables", type: "textarea", required: true },
      { key: "payment_amount", label: "Payment Amount", type: "text", required: true },
      { key: "payment_schedule", label: "Payment Schedule", type: "select", required: true, options: ["monthly", "milestone", "upon_completion", "net_30"] },
      { key: "term_start", label: "Term Start Date", type: "date", required: true },
      { key: "term_end", label: "Term End Date", type: "date", required: true },
      { key: "termination_notice_days", label: "Termination Notice (days)", type: "number", required: true },
      { key: "ip_ownership", label: "IP Ownership", type: "select", required: true, options: ["client", "provider", "shared"] },
      { key: "liability_cap", label: "Liability Cap", type: "text", required: true },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },

  contractor_agreement: {
    id: "contractor_agreement",
    name: "Independent Contractor Agreement",
    file: "templates/contractor-agreement-template.docx",
    description: "Engaging freelancers with clear non-employee classification, scope, and IP terms",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "company_name", label: "Company Name", type: "text", required: true },
      { key: "company_address", label: "Company Address", type: "text", required: true },
      { key: "contractor_name", label: "Contractor Name", type: "text", required: true },
      { key: "contractor_address", label: "Contractor Address", type: "text", required: true },
      { key: "scope_of_work", label: "Scope of Work", type: "textarea", required: true },
      { key: "compensation_amount", label: "Compensation Amount", type: "text", required: true },
      { key: "compensation_type", label: "Compensation Type", type: "select", required: true, options: ["hourly", "fixed_project", "retainer"] },
      { key: "payment_terms", label: "Payment Terms", type: "select", required: true, options: ["net_15", "net_30", "upon_completion", "biweekly"] },
      { key: "term_start", label: "Start Date", type: "date", required: true },
      { key: "term_end", label: "End Date", type: "date", required: true },
      { key: "termination_notice_days", label: "Termination Notice (days)", type: "number", required: true },
      { key: "ip_ownership", label: "IP Ownership", type: "select", required: true, options: ["company", "contractor", "shared"] },
      { key: "equipment_provided", label: "Equipment Provided", type: "select", required: true, options: ["yes", "no"] },
      { key: "non_compete_months", label: "Non-Compete Period (months)", type: "number", required: true },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "contractor_signatory", label: "Contractor Signatory Name", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  //  STAGE 3: FUNDRAISING
  // ═══════════════════════════════════════════════════════════

  safe: {
    id: "safe",
    name: "SAFE (Simple Agreement for Future Equity)",
    file: "templates/safe-template.docx",
    description: "YC-style pre-seed/seed fundraising instrument with valuation cap and discount",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "company_name", label: "Company Name", type: "text", required: true },
      { key: "company_type", label: "Company Entity Type", type: "select", required: true, options: ["corporation", "LLC", "partnership"] },
      { key: "company_jurisdiction", label: "Company Jurisdiction", type: "text", required: true },
      { key: "company_address", label: "Company Address", type: "text", required: true },
      { key: "investor_name", label: "Investor Name", type: "text", required: true },
      { key: "investor_address", label: "Investor Address", type: "text", required: true },
      { key: "investment_amount", label: "Investment Amount ($)", type: "text", required: true },
      { key: "valuation_cap", label: "Valuation Cap ($)", type: "text", required: true },
      { key: "discount_rate", label: "Discount Rate (%)", type: "number", required: true },
      { key: "pro_rata_rights", label: "Pro Rata Rights", type: "select", required: true, options: ["yes", "no"] },
      { key: "mfn_clause", label: "Most Favored Nation Clause", type: "select", required: true, options: ["yes", "no"] },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },

  advisory_agreement: {
    id: "advisory_agreement",
    name: "Advisory Agreement",
    file: "templates/advisory-agreement-template.docx",
    description: "Bringing on advisors with equity compensation, defined scope, and vesting",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "company_name", label: "Company Name", type: "text", required: true },
      { key: "company_address", label: "Company Address", type: "text", required: true },
      { key: "advisor_name", label: "Advisor Name", type: "text", required: true },
      { key: "advisor_address", label: "Advisor Address", type: "text", required: true },
      { key: "advisory_role", label: "Advisory Role Title", type: "text", required: true },
      { key: "responsibilities", label: "Advisor Responsibilities", type: "textarea", required: true },
      { key: "time_commitment", label: "Time Commitment", type: "text", required: true },
      { key: "equity_percentage", label: "Equity Compensation (%)", type: "text", required: true },
      { key: "vesting_months", label: "Vesting Period (months)", type: "number", required: true },
      { key: "cliff_months", label: "Cliff Period (months)", type: "number", required: true },
      { key: "term_months", label: "Agreement Term (months)", type: "number", required: true },
      { key: "confidentiality_term_years", label: "Confidentiality Term (years)", type: "number", required: true },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "advisor_signatory", label: "Advisor Signatory Name", type: "text", required: true },
      { key: "company_signatory", label: "Company Signatory Name", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  //  STAGE 4: HIRING & ONBOARDING
  // ═══════════════════════════════════════════════════════════

  employment_contract: {
    id: "employment_contract",
    name: "Employment Contract / Offer Letter",
    file: "templates/employment-contract-template.docx",
    description: "Formal employment terms including compensation, benefits, equity, and termination provisions",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "company_name", label: "Company Name", type: "text", required: true },
      { key: "company_address", label: "Company Address", type: "text", required: true },
      { key: "employee_name", label: "Employee Name", type: "text", required: true },
      { key: "employee_address", label: "Employee Address", type: "text", required: true },
      { key: "position_title", label: "Position Title", type: "text", required: true },
      { key: "department", label: "Department", type: "text", required: true },
      { key: "reporting_to", label: "Reports To", type: "text", required: true },
      { key: "employment_type", label: "Employment Type", type: "select", required: true, options: ["full_time", "part_time", "temporary"] },
      { key: "start_date", label: "Start Date", type: "date", required: true },
      { key: "salary_amount", label: "Salary Amount", type: "text", required: true },
      { key: "salary_frequency", label: "Salary Frequency", type: "select", required: true, options: ["annually", "monthly", "biweekly"] },
      { key: "bonus_structure", label: "Bonus Structure", type: "textarea", required: false },
      { key: "equity_grant", label: "Equity Grant", type: "text", required: false },
      { key: "benefits_description", label: "Benefits Description", type: "textarea", required: true },
      { key: "vacation_days", label: "Vacation Days Per Year", type: "number", required: true },
      { key: "probation_months", label: "Probation Period (months)", type: "number", required: true },
      { key: "termination_notice_days", label: "Termination Notice (days)", type: "number", required: true },
      { key: "work_location", label: "Work Location", type: "text", required: true },
      { key: "remote_policy", label: "Remote Work Policy", type: "select", required: true, options: ["onsite", "hybrid", "remote"] },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "company_signatory", label: "Company Signatory Name", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },

  employee_nda: {
    id: "employee_nda",
    name: "Employee NDA / Confidentiality Agreement",
    file: "templates/employee-nda-template.docx",
    description: "Protects company secrets with obligations tailored to the employment relationship",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "company_name", label: "Company Name", type: "text", required: true },
      { key: "company_address", label: "Company Address", type: "text", required: true },
      { key: "employee_name", label: "Employee Name", type: "text", required: true },
      { key: "employee_title", label: "Employee Title", type: "text", required: true },
      { key: "confidential_info_description", label: "Confidential Information Description", type: "textarea", required: true },
      { key: "exclusions", label: "Exclusions from Confidentiality", type: "textarea", required: true },
      { key: "obligations_duration_years", label: "Obligations Duration (years)", type: "number", required: true },
      { key: "return_of_materials_days", label: "Return of Materials (days)", type: "number", required: true },
      { key: "non_solicitation_months", label: "Non-Solicitation Period (months)", type: "number", required: true },
      { key: "remedy_description", label: "Remedies Description", type: "textarea", required: true },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "company_signatory", label: "Company Signatory Name", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },

  invention_assignment: {
    id: "invention_assignment",
    name: "Employee Invention Assignment Agreement",
    file: "templates/invention-assignment-template.docx",
    description: "Ensures all employee-created IP during employment belongs to the company",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "company_name", label: "Company Name", type: "text", required: true },
      { key: "company_address", label: "Company Address", type: "text", required: true },
      { key: "employee_name", label: "Employee Name", type: "text", required: true },
      { key: "employee_title", label: "Employee Title", type: "text", required: true },
      { key: "scope_of_inventions", label: "Scope of Inventions Covered", type: "textarea", required: true },
      { key: "prior_inventions", label: "Prior Inventions Excluded", type: "textarea", required: true },
      { key: "disclosure_requirements", label: "Disclosure Requirements", type: "textarea", required: true },
      { key: "moral_rights_waiver", label: "Moral Rights Waiver", type: "select", required: true, options: ["yes", "no"] },
      { key: "works_for_hire", label: "Works Made for Hire", type: "select", required: true, options: ["yes", "no"] },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "company_signatory", label: "Company Signatory Name", type: "text", required: true },
      { key: "employee_signatory", label: "Employee Signatory Name", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },

  at_will_employment: {
    id: "at_will_employment",
    name: "At-Will Employment Agreement",
    file: "templates/at-will-employment-template.docx",
    description: "Clarifies employment-at-will status with formal acknowledgment",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "company_name", label: "Company Name", type: "text", required: true },
      { key: "company_address", label: "Company Address", type: "text", required: true },
      { key: "employee_name", label: "Employee Name", type: "text", required: true },
      { key: "position_title", label: "Position Title", type: "text", required: true },
      { key: "start_date", label: "Start Date", type: "date", required: true },
      { key: "salary_amount", label: "Salary Amount", type: "text", required: true },
      { key: "at_will_notice_period", label: "Notice Period (if any)", type: "text", required: true },
      { key: "handbook_acknowledgment", label: "Handbook Acknowledgment", type: "select", required: true, options: ["yes", "no"] },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "company_signatory", label: "Company Signatory Name", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },

  non_compete: {
    id: "non_compete",
    name: "Non-Compete / Non-Solicitation Agreement",
    file: "templates/non-compete-template.docx",
    description: "Prevents employees from competing with the company or soliciting its clients and employees",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "company_name", label: "Company Name", type: "text", required: true },
      { key: "company_address", label: "Company Address", type: "text", required: true },
      { key: "employee_name", label: "Employee Name", type: "text", required: true },
      { key: "employee_title", label: "Employee Title", type: "text", required: true },
      { key: "non_compete_months", label: "Non-Compete Duration (months)", type: "number", required: true },
      { key: "geographic_scope", label: "Geographic Scope", type: "text", required: true },
      { key: "restricted_activities", label: "Restricted Activities", type: "textarea", required: true },
      { key: "non_solicitation_months", label: "Non-Solicitation Duration (months)", type: "number", required: true },
      { key: "non_solicitation_scope", label: "Non-Solicitation Scope", type: "textarea", required: true },
      { key: "consideration", label: "Consideration", type: "text", required: true },
      { key: "garden_leave_months", label: "Garden Leave Period (months)", type: "number", required: false },
      { key: "enforcement_mechanism", label: "Enforcement Mechanism", type: "select", required: true, options: ["injunctive_relief", "liquidated_damages", "both"] },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "company_signatory", label: "Company Signatory Name", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  //  STAGE 5: COMPLIANCE
  // ═══════════════════════════════════════════════════════════

  privacy_policy: {
    id: "privacy_policy",
    name: "Privacy Policy",
    file: "templates/privacy-policy-template.docx",
    description: "Required policy for any product or service collecting user data (GDPR/CCPA aware)",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "company_name", label: "Company Name", type: "text", required: true },
      { key: "company_address", label: "Company Address", type: "text", required: true },
      { key: "website_url", label: "Website URL", type: "text", required: true },
      { key: "contact_email", label: "Contact Email", type: "text", required: true },
      { key: "data_collected", label: "Types of Data Collected", type: "textarea", required: true },
      { key: "data_usage", label: "How Data Is Used", type: "textarea", required: true },
      { key: "data_sharing", label: "Data Sharing / Third Parties", type: "textarea", required: true },
      { key: "data_retention_period", label: "Data Retention Period", type: "text", required: true },
      { key: "cookie_usage", label: "Cookie / Tracking Policy", type: "textarea", required: true },
      { key: "user_rights", label: "User Rights", type: "textarea", required: true },
      { key: "children_policy", label: "Children's Data Policy", type: "select", required: true, options: ["collects_under_13", "does_not_collect"] },
      { key: "dpo_contact", label: "Data Protection Officer Contact", type: "text", required: true },
      { key: "last_updated", label: "Last Updated Date", type: "date", required: true },
    ],
  },

  terms_of_service: {
    id: "terms_of_service",
    name: "Terms of Service",
    file: "templates/terms-of-service-template.docx",
    description: "Governs use of a product or platform including liability, IP, and dispute resolution",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "company_name", label: "Company Name", type: "text", required: true },
      { key: "company_address", label: "Company Address", type: "text", required: true },
      { key: "website_url", label: "Website / App URL", type: "text", required: true },
      { key: "service_description", label: "Service Description", type: "textarea", required: true },
      { key: "eligibility_age", label: "Minimum Age Requirement", type: "number", required: true },
      { key: "acceptable_use", label: "Acceptable Use Policy", type: "textarea", required: true },
      { key: "user_content_rights", label: "User Content Rights", type: "select", required: true, options: ["user_retains", "company_license", "company_owns"] },
      { key: "subscription_terms", label: "Subscription / Billing Terms", type: "textarea", required: true },
      { key: "liability_cap", label: "Liability Cap", type: "text", required: true },
      { key: "warranty_disclaimer", label: "Warranty Disclaimer", type: "textarea", required: true },
      { key: "termination_conditions", label: "Termination Conditions", type: "textarea", required: true },
      { key: "dispute_resolution", label: "Dispute Resolution", type: "select", required: true, options: ["arbitration", "litigation", "mediation"] },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "contact_email", label: "Contact Email", type: "text", required: true },
      { key: "last_updated", label: "Last Updated Date", type: "date", required: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  //  STAGE 6: OFFBOARDING / SEPARATION
  // ═══════════════════════════════════════════════════════════

  termination_letter: {
    id: "termination_letter",
    name: "Employee Termination / Layoff Letter",
    file: "templates/termination-letter-template.docx",
    description: "Formal notice of employment termination with severance, benefits, and next steps",
    fields: [
      { key: "letter_date", label: "Letter Date", type: "date", required: true },
      { key: "company_name", label: "Company Name", type: "text", required: true },
      { key: "company_address", label: "Company Address", type: "text", required: true },
      { key: "employee_name", label: "Employee Name", type: "text", required: true },
      { key: "employee_title", label: "Employee Title", type: "text", required: true },
      { key: "employee_address", label: "Employee Address", type: "text", required: true },
      { key: "manager_name", label: "Manager Name", type: "text", required: true },
      { key: "manager_title", label: "Manager Title", type: "text", required: true },
      { key: "termination_date", label: "Last Day of Employment", type: "date", required: true },
      { key: "reason_for_termination", label: "Reason for Termination", type: "select", required: true, options: ["layoff", "position_elimination", "performance", "restructuring", "mutual"] },
      { key: "severance_offered", label: "Severance Offered", type: "select", required: true, options: ["yes", "no"] },
      { key: "severance_details", label: "Severance Details", type: "textarea", required: false },
      { key: "benefits_end_date", label: "Benefits End Date", type: "date", required: true },
      { key: "cobra_eligible", label: "COBRA Eligible", type: "select", required: true, options: ["yes", "no"] },
      { key: "final_paycheck_date", label: "Final Paycheck Date", type: "date", required: true },
      { key: "return_of_property_date", label: "Return of Property By", type: "date", required: true },
      { key: "contact_person", label: "HR Contact Person", type: "text", required: true },
      { key: "company_signatory", label: "Company Signatory Name", type: "text", required: true },
    ],
  },

  severance_agreement: {
    id: "severance_agreement",
    name: "Severance Agreement",
    file: "templates/severance-agreement-template.docx",
    description: "Separation terms including severance pay, benefits continuation, and release of claims",
    fields: [
      { key: "effective_date", label: "Effective Date", type: "date", required: true },
      { key: "company_name", label: "Company Name", type: "text", required: true },
      { key: "company_address", label: "Company Address", type: "text", required: true },
      { key: "employee_name", label: "Employee Name", type: "text", required: true },
      { key: "employee_address", label: "Employee Address", type: "text", required: true },
      { key: "employee_title", label: "Employee Title", type: "text", required: true },
      { key: "termination_date", label: "Termination Date", type: "date", required: true },
      { key: "severance_amount", label: "Severance Amount", type: "text", required: true },
      { key: "severance_schedule", label: "Severance Payment Schedule", type: "select", required: true, options: ["lump_sum", "installments", "salary_continuation"] },
      { key: "severance_duration_months", label: "Severance Duration (months)", type: "number", required: true },
      { key: "benefits_continuation_months", label: "Benefits Continuation (months)", type: "number", required: true },
      { key: "equity_treatment", label: "Equity Treatment", type: "textarea", required: true },
      { key: "outplacement_services", label: "Outplacement Services", type: "select", required: true, options: ["yes", "no"] },
      { key: "non_disparagement", label: "Non-Disparagement", type: "select", required: true, options: ["mutual", "one_way", "none"] },
      { key: "non_compete_months", label: "Post-Separation Non-Compete (months)", type: "number", required: true },
      { key: "reference_policy", label: "Reference Policy", type: "textarea", required: true },
      { key: "consideration_period_days", label: "Consideration Period (days)", type: "number", required: true },
      { key: "revocation_period_days", label: "Revocation Period (days)", type: "number", required: true },
      { key: "governing_law_jurisdiction", label: "Governing Law Jurisdiction", type: "text", required: true },
      { key: "company_signatory", label: "Company Signatory Name", type: "text", required: true },
      { key: "signature_date", label: "Signature Date", type: "date", required: true },
    ],
  },
};
