/**
 * Drizzle schema for the Client Prospector feature.
 *
 * This file defines the client_prospector_jobs database table which stores
 * every prospecting search job. When a user submits a prospecting request
 * (e.g. "find law firms near Austin that need IT consulting"), a row is
 * created here with status "queued". As the Inngest background job progresses
 * through the pipeline (planning → searching → scoring), the status column
 * is updated. Once done, the scored results are written into the results
 * JSONB column and the status flips to "completed".
 *
 * This mirrors the pattern used in src/server/db/schema/trend-search.ts.
 */

import { sql } from "drizzle-orm";
import type { InferSelectModel } from "drizzle-orm";
import {
    bigint,
    doublePrecision,
    index,
    integer,
    jsonb,
    text,
    timestamp,
    varchar,
} from "drizzle-orm/pg-core";

// ProspectResult is the shape of each scored business lead (name, address,
// relevanceScore 0-100, rationale, etc.). We store an array of them as JSONB.
import type { ProspectResult } from "~/lib/tools/client-prospector/types";

// company is the parent table — every job belongs to a company.
import { company } from "./base";

// pgTable is a helper that prefixes all table names with "pdr_ai_v2_"
// so the actual SQL table name becomes "pdr_ai_v2_client_prospector_jobs".
import { pgTable } from "./helpers";

// ─── Status Enum ─────────────────────────────────────────────────────────────
// These are the possible states a prospector job can be in.
// The pipeline moves through them in order:
//   queued → planning → searching → scoring → completed
// If anything fails after retries, it goes to "failed".
export const clientProspectorJobStatusEnum = [
    "queued",      // Job created, waiting for Inngest to pick it up
    "planning",    // LLM is generating Foursquare search parameters
    "searching",   // Calling Foursquare API for each planned search
    "scoring",     // LLM is ranking/scoring the found businesses
    "completed",   // Pipeline finished successfully, results are available
    "failed",      // Pipeline failed after all retries, errorMessage has details
] as const;

// ─── Table Definition ────────────────────────────────────────────────────────
// This is the Drizzle equivalent of a CREATE TABLE statement.
// First arg: table name (will be prefixed with "pdr_ai_v2_")
// Second arg: column definitions
// Third arg: indexes for query performance
export const clientProspectorJobs = pgTable(
    "client_prospector_jobs",
    {
        // ── Primary key ──────────────────────────────────────────────────
        // UUID generated by the API route when the job is created.
        id: varchar("id", { length: 256 }).primaryKey(),

        // ── Multi-tenancy ────────────────────────────────────────────────
        // Foreign key to the company table. This is how we enforce data
        // isolation — every query filters by company_id so company A
        // can never see company B's jobs. onDelete: "cascade" means
        // if a company is deleted, all their prospector jobs are too.
        companyId: bigint("company_id", { mode: "bigint" })
            .notNull()
            .references(() => company.id, { onDelete: "cascade" }),

        // Who initiated this search (Clerk user ID). Used for audit trail,
        // but isolation is enforced at the company level, not user level.
        userId: varchar("user_id", { length: 256 }).notNull(),

        // ── Pipeline status ──────────────────────────────────────────────
        // Current state of the background job. The enum constraint ensures
        // only valid status values can be stored. Defaults to "queued"
        // when the row is first inserted.
        status: varchar("status", {
            length: 50,
            enum: clientProspectorJobStatusEnum,
        })
            .notNull()
            .default("queued"),

        // ── User input ───────────────────────────────────────────────────
        // The original search query (e.g. "find restaurants that need marketing")
        query: text("query").notNull(),

        // Description of the user's company (e.g. "We are a marketing agency
        // specializing in social media"). The LLM uses this to score how
        // relevant each found business is as a potential client.
        companyContext: text("company_context").notNull(),

        // ── Location ─────────────────────────────────────────────────────
        // Latitude and longitude for the search center point.
        // Stored as doublePrecision (64-bit float) for GPS accuracy.
        // If the user provided a string like "Austin, TX", it gets
        // resolved to lat/lng BEFORE the job is created.
        locationLat: doublePrecision("location_lat").notNull(),
        locationLng: doublePrecision("location_lng").notNull(),

        // Search radius in meters. Default is 5000 (5km), max is 50000 (50km).
        radius: integer("radius").notNull().default(5000),

        // ── Optional filters ─────────────────────────────────────────────
        // Foursquare category IDs or names the user wants to filter by.
        // Stored as JSONB array of strings. Nullable — if null, the LLM
        // infers appropriate categories from the query.
        // Example: ["13065", "13066"] (Foursquare IDs for restaurants)
        categories: jsonb("categories").$type<string[]>(),

        // ── Pipeline output ──────────────────────────────────────────────
        // The scored business results. Null until the pipeline completes.
        // Stored as a JSONB array of ProspectResult objects, each containing:
        //   { fsqId, name, address, location, categories, phone?, website?,
        //     rating?, relevanceScore (0-100), rationale }
        // Up to 10 results, ranked by relevanceScore descending.
        results: jsonb("results").$type<ProspectResult[]>(),

        // ── Error tracking ───────────────────────────────────────────────
        // If the pipeline fails, the error message is stored here.
        // Null when status is not "failed".
        errorMessage: text("error_message"),

        // ── Timestamps ───────────────────────────────────────────────────
        // When the job was created. Auto-set by the database.
        createdAt: timestamp("created_at", { withTimezone: true })
            .default(sql`CURRENT_TIMESTAMP`)
            .notNull(),

        // When the job finished (either completed or failed). Null while
        // the job is still running. Set by the Inngest function.
        completedAt: timestamp("completed_at", { withTimezone: true }),

        // Auto-updated whenever any column in the row changes.
        // Drizzle's $onUpdate hook handles this in the application layer.
        updatedAt: timestamp("updated_at", { withTimezone: true }).$onUpdate(
            () => new Date()
        ),
    },

    // ── Indexes ──────────────────────────────────────────────────────────────
    // These speed up common queries. Without indexes, PostgreSQL would have
    // to scan every row in the table to find matches.
    (table) => ({
        // Look up all jobs for a specific company (used by GET /api/client-prospector)
        companyIdIdx: index("client_prospector_jobs_company_id_idx").on(table.companyId),

        // Filter jobs by status (e.g. find all "queued" jobs)
        statusIdx: index("client_prospector_jobs_status_idx").on(table.status),

        // Compound index for the most common query pattern:
        // "get all jobs for company X with status Y"
        companyStatusIdx: index("client_prospector_jobs_company_status_idx").on(
            table.companyId,
            table.status
        ),
    })
);

// ── Exported Type ────────────────────────────────────────────────────────────
// InferSelectModel extracts the TypeScript type from the table definition.
// This gives you a type like:
//   { id: string; companyId: bigint; userId: string; status: string; ... }
// Use this when you SELECT rows from the table — Drizzle will return
// objects matching this shape.
export type ClientProspectorJob = InferSelectModel<typeof clientProspectorJobs>;
